import type { Metadata } from "next";
import { Marcellus } from "next/font/google";
import "./globals.css";
import SharedLayout from "./components/shared/SharedLayout";

const marcellus = Marcellus({
  weight: "400",
  style: "normal",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={marcellus.className}>
        <div className="w-full px-5">
          <SharedLayout>{children}</SharedLayout>
        </div>
      </body>
    </html>
  );
}
